### ISSUE TITLE
GetUserData, Second http call

### ISSUE THREAD

**Issue by TopalSinek** [DjCedrics/Augma#23]
fetchuser da get user requesti calisiyo ikinci userdata requestini yaparken makehttpcal functioninin icinde Outputstream os= connection.getOutputstreamde exception atiyo. Su an acilmiyo o yuzden :)

**Comment by TopalSinek** [comment]
sorun networkonmain thread, yani main thread de network operation yapmaya calistigi icin oluyomus asyncronous task olarak yapin diyolar. Bizimki zaten oyle calismiyomuydu ?

**Comment by TopalSinek** [comment]
I kinda solved it, but it is a bad solution.

**Comment by aburaksahin** [comment]
I'll still take a look at it. Regardless, I suggest that we should keep enforcing the service dependent design pattern that I originally intended to establish. This bug seems to be a by-product of breaking that original design. Also, we don't have any sort of assurance that by no means such by-product errors will cease to occur.
